.TH "Kevin Faro" 1 "2017-05-08" "http://github.com/kevinfaro" "Good Ideas"
.SH NAME
Kevin Faro
.SH SYNOPSIS
.P
Full-stack engineer interested in solving hard problems.
.SH DESCRIPTION
.P
Highly motivated software engineer with experience in the full life cycle of software development. Involved in and responsible for gathering requirements, software/database design, implementation and testing. 
Diligent professional who strives to meet business needs through proper planning and execution by utilizing sound software engineering principles and design patterns.
.SH OPTIONS
.TP
.BR \-F ", " \-\-force \fR
Force him to work for you.
(This is not the preferred option.)
.TP
.BR \-I "," \-\-interview \fR
Interview him. (Default)
.SH AUTHOR
.P 
Written by Kevin Faro (definitely not biased in any way).
.SH HISTORY
.TP
.BR 2012\-PRESENT 
Tetra Concepts
.TP
.BR 2008\-2012 
Pyxis Engineering
.TP
.BR 2004\-2008 
SAIC
.SH EDUCATION
.TP
.BR 2006\-2009 
M.S. Computer Science - John's Hopkins
.TP
.BR 2000\-2004 
B.S. Computer Science - University of MD
.SH SKILLS
.TP
.BR Java/Scala 
(10+ years Java & 2 years Scala) Building business critical applications and analytics.
.TP
.BR Python
(7+ years) Used for data cleaning and algorithm prototyping.
.TP
.BR Hadoop
(5+ years) Writing analytics in Java Map/Reduce as well as Apache Scalding against HDFS, Accumulo, and HBase.
.TP
.BR Docker
(1 year) Building and deploying containerized applications on top of Apache Mesos.
.TP
.BR Linux/Bash
(10+ years) Used as a development and deployment environment.
.sp
.I P.S. I \&hearts; awk!
.SH EXAMPLES
.TP
.BR Github
https://github.com/kevin-faro
.TP
.BR LinkedIn
https://www.linkedin.com/in/kevinfaro/
.TP
.BR CodeEval
https://www.codeeval.com/public/8b8f5d16ddd8e332e4da6f7e63fe3c2e7621ead4/
.TP
.BR Codility
https://codility.com/cert/view/certF2XZ7K-VXBRMUPSQ8JZY8UC/
